# Generated by Django 4.0.2 on 2022-03-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=1024, null=True)),
                ('last_login', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
