# Generated by Django 4.0.2 on 2022-03-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_member_member_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='ユーザID')),
                ('password', models.CharField(max_length=1024, null=True)),
                ('last_login', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'ユーザ',
            },
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
