# Generated by Django 4.0.2 on 2022-03-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_authuser_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authuser',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='管理サイトアクセス権限'),
        ),
    ]
