# Generated by Django 4.0.2 on 2022-03-31 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_authuser_admin_authuser_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'verbose_name': 'User'},
        ),
    ]
