# Generated by Django 4.0.2 on 2022-03-31 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_authuser_staff_alter_authuser_admin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authuser',
            table='user',
        ),
    ]
