# Generated by Django 4.0.2 on 2022-02-25 08:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='タスク名')),
                ('content', models.CharField(blank=True, max_length=200, null=True, verbose_name='詳細')),
                ('condition', models.CharField(choices=[('Nothing', '特になし'), ('Home', '自宅'), ('Emergency', '緊急'), ('Shopping', '買い物')], default=('Nothing', '特になし'), max_length=200, verbose_name='条件')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
