# Generated by Django 4.0.2 on 2022-03-02 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasque', '0002_remove_task_content_task_detail_alter_task_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='condition',
            new_name='tags',
        ),
    ]
