# Generated by Django 4.0.2 on 2022-03-02 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasque', '0003_rename_condition_task_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ステータス名')),
                ('sort_order', models.PositiveSmallIntegerField(verbose_name='ソート順')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='tasque.taskstatus', verbose_name='ステータス'),
        ),
    ]
