# Generated by Django 4.0.2 on 2022-03-02 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasque', '0004_taskstatus_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='タグ')),
                ('sort_order', models.PositiveSmallIntegerField(verbose_name='ソート順')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasque.tasktags', verbose_name='タグ'),
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
