# Generated by Django 4.0.2 on 2022-03-02 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasque', '0005_tasktags_alter_task_status_delete_taskstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskTags',
            new_name='TaskTag',
        ),
    ]
