# Generated by Django 4.0.2 on 2022-03-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasque', '0007_remove_task_status_task_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'TODO'), (1, '完了'), (2, 'キャンセル'), (3, 'WIP')], default=0, verbose_name='ステータス'),
        ),
    ]
