# Generated by Django 4.0.2 on 2022-03-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasque', '0008_alter_task_options_remove_task_tags_task_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'TODO'), (1, '完了'), (2, '期限切れ')], default=0, verbose_name='ステータス'),
        ),
    ]
