# Generated by Django 4.0.2 on 2022-03-06 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasque', '0009_alter_task_options_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='updated_at',
            new_name='finished_at',
        ),
    ]
