# Generated by Django 4.0.2 on 2022-03-07 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasque', '0011_alter_task_finished_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktag',
            name='sort_order',
        ),
    ]
