# Generated by Django 4.0.2 on 2022-03-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasque', '0012_remove_tasktag_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完了日時'),
        ),
    ]
