# Generated by Django 4.0.2 on 2022-03-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasque', '0013_alter_task_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tasque.tasktag', verbose_name='タグ'),
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
        migrations.AlterModelTable(
            name='tasktag',
            table='tag',
        ),
    ]
