# Generated by Django 4.0.2 on 2022-03-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasque', '0014_alter_task_tag_alter_task_table_alter_tasktag_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='期限'),
        ),
    ]
